var arreglo=['lapiz','macador','regla','cuadernos']
document.write(arreglo.join('')+'<br>')
document.write('cantidad de valores'+arreglo.length)
document.write('<br>')
arreglo.push('cartuchera')
document.write('elementro agregado:'+arreglo.join(''))
document.write('br')
arreglo.unshift('lapicera')
document.write('elemento agregado'+arereglado.join(''))
arreglo.shift()
document.write('1° elemento eliminado'+arreglo.join(''))
